name: CI

permissions: {}

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
          submodules: recursive

      - name: Install modules
        run: yarn install --frozen-lockfile

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: forge --version

      - name: Run lint
        run: yarn lint

      - name: Run Forge build
        run: forge build --sizes

      - name: Run Forge tests
        run: forge test -vvv

      - name: Run Forge coverage
        run: forge coverage --no-match-coverage '(script|test)' --report lcov

      - name: Report coverage
        if: github.event_name == 'pull_request'
        uses: romeovs/lcov-reporter-action@v0.4.0
        with:
          lcov-file: ./lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
